# Generated by Django 6.0.6 on 2026-07-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
