# Generated by Django 6.0.6 on 2026-07-09 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='department',
            field=models.CharField(choices=[('Computer Science and Technology', 'Computer Science and Technology'), ('Mechanical Technology', 'Mechanical Technology'), ('Electrical Technology', 'Electrical Technology'), ('Electronics Technology', 'Electronics Technology'), ('Civil Technology', 'Civil Technology'), ('Electro-medical Technology', 'Electro-medical Technology'), ('RAC Technology', 'RAC Technology'), ('Non-Tech', 'Non-Tech')], max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='shelf_number',
            field=models.CharField(choices=[('A1', 'A1'), ('A2', 'A2'), ('A3', 'A3'), ('B1', 'B1'), ('B2', 'B2'), ('B3', 'B3'), ('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('D1', 'D1')], max_length=10),
        ),
    ]
