# Generated by Django 6.0.6 on 2026-07-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='student_id',
            field=models.CharField(default='UNKNOWN', max_length=20),
            preserve_default=False,
        ),
    ]
