# Generated by Django 6.0.6 on 2026-07-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_issue_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='Department',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='Shift',
            field=models.CharField(default='UNKNOWN', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='Student_name',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
    ]
