# Generated by Django 6.0.6 on 2026-07-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_issue_department_issue_shift_issue_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='Shift',
            new_name='shift',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='Student_name',
            new_name='student_name',
        ),
        migrations.AddField(
            model_name='issue',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
