# Generated by Django 6.0.6 on 2026-07-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_rename_department_issue_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='department',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='shift',
            new_name='Shift',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='student_name',
            new_name='Student_name',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='returned_at',
        ),
    ]
