# Generated by Django 6.0.6 on 2026-07-09 21:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0006_rename_department_issue_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='semester',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th')], default=django.utils.timezone.now, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='issue',
            name='department',
            field=models.CharField(choices=[('Computer Science and Technology', 'Computer Science and Technology'), ('Mechanical Technology', 'Mechanical Technology'), ('Electrical Technology', 'Electrical Technology'), ('Electronics Technology', 'Electronics Technology'), ('Civil Technology', 'Civil Technology'), ('Electro-medical Technology', 'Electro-medical Technology'), ('RAC Technology', 'RAC Technology'), ('Non-Tech', 'Non-Tech')], max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='shift',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Day', 'Day')], max_length=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='student_id',
            field=models.CharField(max_length=5),
        ),
    ]
